### ISSUE TITLE
Make sure websockets does full binary communication!

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/esp82xx#13]

**Comment by con-f-use** [comment]
What? Also old...

**Comment by cnlohr** [comment]
hhhnnnggggg  I keep pushing this off, though it would be REALLY helpful.  There are bits that need to be set in the responses as well as a change in the javascript.  It would be super cool to be able to just send binary data instead of needing to hex-encode large binary chunks.

**Comment by con-f-use** [comment]
I think I did something like this already somewhere in the code. Might be in on of my projects not on git. Just didn't get what you mean at first.

**Comment by cnlohr** [comment]
Ah! Yes.  Hmm, I SHOULD have tried it last night instead of jumping directly to using hex encoding.

**Comment by con-f-use** [comment]
Found it. It was in the led [color setting web-interface](https://github.com/cnlohr/esp8266ws2812i2s/blob/master/web/page/main.js#L80) for [esp8266ws2812i2c](https://github.com/cnlohr/esp8266ws2812i2s).

**Comment by cnlohr** [comment]
That's still using hexpairs.

**Comment by con-f-use** [comment]
Well the data `qDat` is an array of 8 byte `ints`. Is not converted or decoded to/from hex, i.e. it's not only using the 0-9 & a-f. Not sure what else you mean.

**Comment by cnlohr** [comment]
Hmm... I think it is anywhere zero and reserved chars may be used.

http.c. line 643.  The opcode of the websockets packet is still 1.

**Comment by cnlohr** [comment]
I think I just restricted the possible values to preclude it from hitting 0.

**Comment by cnlohr** [comment]
Ah! Ok, so changing that kinda makes things... work... ish... I'm going to try to change it in the backend javascript maybe to autodetect?

**Comment by cnlohr** [comment]
no need... but now I am once again battling the git.
