### ISSUE TITLE
Custom command Cmd_WiFi "WR" not working on web

### ISSUE THREAD

**Issue by brainstorm** [cnlohr/esp82xx#23]
Hi @cnlohr,

Sorry to bother you with this, but I was about to write a method to return a wireless scan as an array, and voila, there you have already a `case` in cmd_WiFi.

But I tried to issue the commands `WR1`, `WR`... to no avail, wonder if it really works via the WebGUI?

**Comment by cnlohr** [comment]
I just changed the way it worked last night so I could free up about 500 bytes of RAM.  I tested it and it worked a-okay.  Are you not seeing positive behavior from the web GUI?

WS first, wait for comms to come back, then WR

**Comment by brainstorm** [comment]
Just tried what you mentioned (WS, wait for comms and then WR) and I just get a `!WR` back :-S

![skarmavbild 2016-08-25 kl 07 46 11](https://cloud.githubusercontent.com/assets/175587/17958212/352edb6c-6a98-11e6-85d5-e6d6dc7e9f8c.png)

**Comment by cnlohr** [comment]
Aaha!  I see a list of APs above there. So, the webpage, itself polls for WR frequently.  Whenever you issue a WS, the device disconnects, scans, and keeps a copy of the scan list around.  Once reconnected, the webpage pulls that list with "WR." Once received, it erases the list on the ESP and boom.  Can't see it anymore.

You might be able to get away with this by closing the "Wifi" tab.

**Comment by brainstorm** [comment]
Yeah, it was exactly that, now I get that array/list back, thanks! ;)
