### ISSUE TITLE
access points created but how to make further setup....i'm new to esp8266

### ISSUE THREAD

**Issue by sarwadenj** [cnlohr/esp82xx#43]
Hi,
how should i make setup at router side. Actually executable toprecorder and process made but i don't know how to made setup at router side.

After "make burn" and "make netburn" it creates its own WiFi Access Point but i am new to esp8266 i don't know how to move forward to get packets.

Thanks.

**Comment by con-f-use** [comment]
You can join an existing WLAN by connecting to the AP, going to 192.168.4.1 in your browser and then scanning and joining the network over the WebGUI. You can toggle pins over the WebUI or by faking the respective requestion. For more than that, you will most likely have to look at the source code and change it.
