### ISSUE TITLE
Automatically getting esp_nonos_sdk?

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/esp82xx#65]
@con-f-use I am not sure how to do this, but every time it takes me forever how to remember how to get esp82xx to pull the esp_nonos_sdk submodule inside esp82xx.

I am gonna make this issue so I at lest can remember...

```
git submodule init
git submodule update
```

from within esp82xx.  But, my question is, how can we automatically detect this?

**Comment by con-f-use** [comment]
Posting here, because I just saw this ant want to be notified per mail rather than just alerted by git.

Will be no problem. I'll get to it this weekend.

**Comment by cnlohr** [comment]
Thank you!  <3 that you have time for feature requests.

**Comment by con-f-use** [comment]
I hope 2fb02df does what you asked.
