### ISSUE TITLE
netburn failing

### ISSUE THREAD

**Issue by bbkiwi** [cnlohr/esp82xx#68]
I'm checking this out. I get !FM4 (MD5 mismatch). 
If I remove -DQUIET_REFLASH it seems to work but gives message 
"Timeout. Good? Maybe?" (a bit of a strange message).

netweb seems to work with either option.

**Comment by cnlohr** [comment]
That is /very/ unusual and I have never seen anything like it, but I am also not on the most recent branch, so I would imagine it has to do with the recent changes.  I really can't make much time to commit to this until next week with Artscape coming up and a number of other events, but, I am curious if this happens if you flash the older esp82xx.

**Comment by bbkiwi** [comment]
I've tried esp82xx earlier commits 21e23b5 before my changes, and 21e23b5 also. Both give the message "Timeout. Good? Maybe?" and the new code does NOT upload. 
I used 79ce49d and got "Timeout. Good? Maybe?" but the new code DID upload. Also lots of stuff was printed on the serial port (which didn't happen with the two cases where the code did not upload).
[SerialOut.txt](https://github.com/cnlohr/esp82xx/files/1164580/SerialOut.txt)


I tried with cc + esp82xx (most recent on my repo branches devwork and devfixes respl.) got the !FM4 once but mostly get "Timeout. Good? Maybe?" and the new code does NOT upload.  So maybe the !FM4 was just a random glitch there.

**Comment by cnlohr** [comment]
oh boy that's weird.  UUggghh I wish I could do this now :(

**Comment by bbkiwi** [comment]
Did more tests.  9641825 uploads OK (gives terminal message "Timeout. Good?.." get serial messages A....E and reboots w cause 2)
adb21e5 and 50afc5e upload OK (gives terminal message "Timeout. Good?.." get serial messages A....E  **but** reboots w cause 4 wdt reset)
21e23b5 FAILS (gives terminal message "Timeout. Good?.." **but** serial messages stop at AB and reboots w cause 4 **wdt reset**) but old code is still running afterwards. (I think the wdt reset is triggered in  Cache_Read_Disable() but I can't see how the earlier commits are that much different)
[testnetburn.txt](https://github.com/cnlohr/esp82xx/files/1167090/testnetburn.txt)

**Comment by bbkiwi** [comment]
FIXED! Submitted pull.

**Comment by bbkiwi** [comment]
Fixed  -DQUIET_REFLASH too. Submitted pull

**Comment by cnlohr** [comment]
So... close issue?

**Comment by bbkiwi** [comment]
Ok.

**Comment by cnlohr** [comment]
Sorry, I just realized that came off the wrong way.  I just wanted to know if everything was golden.  Not badger you for leaving an issue open :(

**Comment by cnlohr** [comment]
I really appreciate the effort you're putting in here!

**Comment by bbkiwi** [comment]
Not a problem, I didn't even realize your post could be taken as badgering :-)

**Comment by con-f-use** [comment]
Just merged everything into master, although #60 and #66 are still open and probably related.
Good work people, ESPecially bbkiwi!
