### ISSUE TITLE
con-f-use needs to check my work

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/esp82xx#8]
@con-f-use 

Can you please check all of the changes I've made.  I have done a lot and I think there's high risk for really messing something up along with possibly misunderstanding your intent for things.

**Comment by con-f-use** [comment]
So far everything looks good. I fixed the shell variable for SDK path thing in #11, though that might have been a mistake. Don't know, why you changed it in the first place.

**Comment by cnlohr** [comment]
everything looks like it works :-D
